project:
  type: website
  output-dir: ../docs

website:
  title: Understanding Cancer Communication
  navbar:
    left:
      - href: data_cleaning.ipynb
        text: Data Cleaning
      - href: eda_hints.qmd
        text: HINTS EDA
      - href: eda-nlp-reddit.qmd
        text: Reddit EDA
      - href: nlp.qmd
        text: NLP
      - href: hints_regression.qmd
        text: HINTS ML 
      - href: reddit_ml.qmd
        text: Reddit ML
      - href: summary.md
        text: Summary
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var author.name >}}] <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    code-fold: true
    theme: cosmo
    toc: true
    embed-resources: true
    # Optional: Uncomment if you want to add your custom styles
    # css: styles.css
